config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_prefix =>'auth'
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get '/autoridades', to: 'pages#autoridades'
  get '/historia', to: 'pages#historia'
  get 'ib', to: 'pages#ib'
  get '/mision', to: 'pages#mision'
  get '/inicial', to: 'pages#inicial'
  get '/oferta_academica', to: 'pages#oferta_academica'
  get '/experiencia_educativa', to: 'pages#experiencia_educativa'

  resources :articles do
    resources :galleries, only: [:show, :create]
  end
  resources :contacts, only: [:new, :create]
  resources :conections, exept: [:update, :edit]



  resources :events
  resources :users, only: [:show, :destroy, :new, :create]
  resources :categories
  resources :posts
  resources :divisions, only: :show
  resources :documents
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :division
  validates :title, presence: true
  validates :subtitle, presence: true
  has_one_attached :photo
  has_many_attached :images
  has_many :galleries, dependent: :destroy
  validate :photo_attach
  paginates_per 12

  private

  def photo_attach
    if photo.attached? == false
      errors.add(:photo, 'tiene que estar presente')
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_articles, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.order(created_at: :desc).page params[:page]
    @divisions = Division.all
  end

  def show
    @divisions = Division.all
    @gallery = Gallery.new
  end

  def new
    if current_user.admin?
      @article = Article.new
    else
      flash[:notice] = "Accesso denegado"
      redirect_to root_path
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_articles
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :subtitle, :content1, :content2, :content3, :photo, :category, :division_id, :url, images: [])
  end
end

app/views/articles/_admin.html.erb
<% if user_signed_in? %>
<% if current_user.admin? %>
<div class="show-admin-container">
  <div>
    <h2>Noticias</h2>
    <%= link_to 'Editar Noticia', edit_article_path(@article), class: 'btn btn-warning btn-block' %>
    <br>
    <%= link_to 'Eliminar Noticia',  @article,  method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-block' %>
  </div>
  <div class="mt-5">
    <% unless @article.galleries.present? %>
    <h2>Crear galeria de fotos</h2>
    <%= simple_form_for([ @article, @gallery ]) do |f| %>
    <%= f.input :title, required: false, label: 'Titulo' %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit 'Crear Galeria', class: 'btn btn-dark btn-block' %>
    <% end %>
  </div>
  <% end %>
  <% else %>
</div>
<% end %>
<% else %>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/main_navbar' %>
<% if current_user.admin? %>
<div class="container">
  <div class="article-new-container">
    <h2>Crear una noticia</h2>
    <%= simple_form_for(@article) do |f| %>
    <%= f.association :division%>
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <%= f.input :content1 %>
    <%= f.input :content2 %>
    <%= f.input :content3 %>
    <%= f.input :url, required: false %>
    <%= f.input :photo, as: :file %>
    <%= f.input :images, as: :file, input_html: { multiple: true }, label: "Archivo PDF" %>
    <%= f.submit 'Crear Noticia', class:"btn btn-primary btn-lg btn-block " %>
    <% end %>
  </div>
</div>
<% else %>
<%= render 'shared/denied' %>
<% end %>

app/views/articles/index.html.erb
<%= render 'shared/main_navbar' %>
<div class="banner-articles" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dw7ox75dg/image/upload/v1585229626/casa_historica_secundario.jpg);">
</div>
<div class="articles-navbar mb-3">
  <% @divisions.each do |division| %>
  <h2><%= link_to division.title.upcase,division_path(division) %></h2>
  <% end %>
  <h2><%= link_to 'TODAS', articles_path %></h2>
</div>
<div class="article-container">
  <% @articles.each do |article| %>
  <%= render 'cards/article_card', article: article %>
  <% end %>
</div>
<div class="mt-5 pb-5">
  <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<%= render 'shared/main_navbar' %>
<% if current_user.admin? %>
<div class="container">
  <div class="article-new-container">
    <h2>Crear una noticia</h2>
    <%= simple_form_for(@article) do |f| %>
    <%= f.association :division, label: 'Categoria' %>
    <%= f.input :title, placeholder: "Titulo", required: false %>
    <%= f.input :subtitle, placeholder: "Subtitulo", required: false %>
    <%= f.input :content1, placeholder: "Primer Contenido", required: false %>
    <%= f.input :content2, placeholder: "Segundo Contenido", required: false %>
    <%= f.input :content3, placeholder: "Tercer Contenido", required: false %>
    <%= f.input :photo, as: :file %>

    <%= f.submit 'Crear Noticia', class:"btn btn-primary btn-lg btn-block " %>
    <% end %>
  </div>
</div>
<% else %>
<%= render 'shared/denied' %>
<% end %>

app/views/articles/show.html.erb
<%= render 'shared/main_navbar' %>
<section id="show-admin-container">
  <%= render 'admin' %>
</section>
<div class="articles-navbar mb-3">
  <% @divisions.each do |division| %>
  <h2><%= link_to division.title.upcase,division_path(division) %></h2>
  <% end %>
  <h2><%= link_to 'TODAS', articles_path %></h2>
</div>
<br><br><br>
<div class="show-articles-wrapper">
  <div class="show-articles-container">
    <div class="show-articles-title">
      <h2><%= @article.title %></h2>
      <h3><%= @article.subtitle %></h3>
    </div>
    <h6><%= @article.created_at.in_time_zone("Buenos Aires").strftime(" %d %b %Y - %I:%M %P") %></h6>
    <%= cl_image_tag(@article.photo.key, :quality=>'auto') %>
    <p><%= @article.content1 %></p>
    <p><%= @article.content2 %></p>
    <p><%= @article.content3 %></p>
    <a href="<%= @article.url %>" target='_blank'><%= @article.url %></a>
    <div class="mt-3">
      <% @article.images.each_with_index do |image, index| %>
      <%= link_to cl_image_path(image.key, flags: 'attachment'), download: "@article.title" do %>
        <p class="mb-2"><i class="fas fa-file-pdf h3 text-danger"></i> Descargar Archivo PDF <%= index + 1 %></p>
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="show-articles-footer">
  </div>
</div>
<div class="show-gallery-wrapper">
  <% @article.galleries.each do |gallery| %>
  <%= render 'shared/gallery', gallery: gallery %>
  <% end %>
</div>
<div class="text-center mt-5 mb-5">
  <%= link_to 'Mas Noticias', articles_path, class: 'btn-article'  %>
</div>