config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_prefix =>'auth'
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get '/autoridades', to: 'pages#autoridades'
  get '/historia', to: 'pages#historia'
  get 'ib', to: 'pages#ib'
  get '/mision', to: 'pages#mision'
  get '/inicial', to: 'pages#inicial'
  get '/oferta_academica', to: 'pages#oferta_academica'
  get '/experiencia_educativa', to: 'pages#experiencia_educativa'

  resources :articles do
    resources :galleries, only: [:show, :create]
  end
  resources :contacts, only: [:new, :create]
  resources :conections, exept: [:update, :edit]



  resources :events
  resources :users, only: [:show, :destroy, :new, :create]
  resources :categories
  resources :posts
  resources :divisions, only: :show
  resources :documents
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_articles.html.erb
<div class="home-container">
  <div class="py-5 my-md-5 text-center">
    <h2 class="font-weight-bold">Novedades</h2>
    <h4>Las últimas noticias del colegio</h4>
  </div>
  <div class="article-container">
    <% @articles.take(6).each do |article| %>
    <%= render 'cards/article_card', article: article %>
    <% end %>
  </div>
  <div class="pt-4 mt-4 mb-5 pb-5 text-center">
    <%= link_to 'Más Noticias', articles_path, class: "btn-article"  %>
  </div>
</div>

app/views/shared/_cards.html.erb
<div class="card-article">
  <%= link_to article_path(article) do %>
  <img src="<%= article.photo %>" alt="">
  <h4><%= article.category %></h4>
  <h2><%= article.title %></h2>
  <% end %>
</div>

app/views/shared/_denied.html.erb
<div class="denied-container">
  <div class='text-center'>
    <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1585140067/san_patricio_logo.png" alt="">
    <h2>ACCESO DENEGADO</h2>
    <%= link_to 'VOLVER', root_path, class: 'btn btn-primary btn-lg'  %>
  </div>
</div>

app/views/shared/_event-cards.html.erb
<%= link_to event_path(event) do %>
<div class="event-container">
  <div class="event-img">
    <img src="<%= event.photo %>" alt="">
  </div>
  <div class="event-content">
    <h2><%= event.title %></h2>
    <h3><i class="far fa-calendar-alt"></i> <strong style="color: grey;"><%= event.date.strftime(' %d/%m/%y') %></strong></h3>
    <h3><i class="far fa-clock"></i> <strong style="color: grey;"> <%= event.time.in_time_zone("Buenos Aires").strftime('%H:%M') %></strong> </h3>
    <p><%= event.description %></p>
  </div>
</div>
<% end %>

app/views/shared/_event_card.html.erb
<div class="main-wrapper-event">
  <%= link_to event_path(event) do  %>
  <div class="main-event-container">
    <div class="main-event-img">
      <img src="<%= event.photo %>" alt="">
    </div>
    <div class="main-event-content">
      <div class="date-box">
        <p><%= event.date.strftime('%b') %></p>
        <h2><%= event.date.strftime('%d') %></h2>
      </div>
    </div>
    <div class="event-card-footer">
      <h2><%= event.title.truncate(30) %></h2>
      <p><i class="far fa-clock"></i> <%= event.time.strftime('%H:%M') %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="guillo" role="alert">
  <%= notice %>  <a href="" class="alert-link">X</a>
</div>
<% end %>
<% if alert %>

<div class="guillo" role="alert">
  <%= alert %> <a href="" class="alert-link">X</a>
</div>
<% end %>

app/views/shared/_gallery.html.erb
<h2>Galeria de Fotos</h2>
<div class="gallery-main-container">
  <% gallery.photos.first(1).each_with_index do |photo, index| %>
  <div class="gallery-container" data-toggle="modal" id="gallery" data-target="#exampleModalCenter">
    <div data-target="#carouselExampleIndicators" data-slide-to="<%= index %>">
      <%= cl_image_tag(photo.key, :quality=>'auto') %>
    </div>
  </div>
  <% end %>
  <% gallery.photos.drop(1).each_with_index do |photo, index| %>
  <div class="gallery-container" data-toggle="modal" id="gallery" data-target="#exampleModalCenter">
    <div data-target="#carouselExampleIndicators" data-slide-to="<%= index + 1 %>">
      <%= cl_image_tag(photo.key, :quality=>'auto') %>
    </div>
  </div>
  <% end %>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-xl">
    <div class="modal-content">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <% gallery.photos.first(1).each_with_index do |photo, index| %>
          <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="active"></li>
          <% end %>
          <% gallery.photos.drop(1).each_with_index do |photo, index| %>
          <li data-target="#carouselExampleIndicators" data-slide-to="<%= index + 1 %>"></li>
          <% end %>
        </ol>
        <div class="carousel-inner">
          <% gallery.photos.first(1).each do |photo| %>
          <div class="carousel-item active">
            <%= cl_image_tag(photo.key, :quality=>'auto') %>
          </div>
          <% end %>
          <% gallery.photos.drop(1).each do |photo| %>
          <div class="carousel-item">
            <%= cl_image_tag(photo.key, :quality=>'auto') %>
          </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_ib.html.erb
<div class="ib-container-1">
  <div class="banner-ib" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://res.cloudinary.com/dw7ox75dg/image/upload/v1589460025/San%20patricio/Captura_de_Pantalla_2020-05-14_a_la_s_09.31.05.jpg);">
    <div class=banner-container-ib>
      <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1584881920/ib-world-school-logo-1-colour-rev.png" alt="">
      <p>
        <span id="banner-typed-text"></span>
      </p>
      <%= link_to 'Conocé más', ib_path, class: "btn-ib" %>
    </div>
  </div>
</div>

app/views/shared/_main-cards.html.erb
<div class="main-card-article">
  <%= link_to article_path(article) do %>
  <div class="main-card-category" style="background-image: linear-gradient(rgba(250,250,250,0.1), rgba(0,0,0,0.7)), url(<%= article.photo %>)">
    <div class="main-card-content">
      <h4><%= article.category %></h4>
      <h2><%= article.title %></h2>
    </div>
  </div>
  <% end %>
</div>
<div class="main-card-article-2">
  <%= link_to article_path(article) do %>
  <img src="<%= article.photo %>" alt="">
  <h4><%= article.category %></h4>
  <h2><%= article.title %></h2>
  <% end %>
</div>

app/views/shared/_main_navbar.html.erb
<div class="navbar navbar-expand-xl navbar-light navbar-main fixed-top ">
  <div>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dw7ox75dg/image/upload/v1585140067/san_patricio_logo.png", class:'sp-img'%>
    <% end %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dw7ox75dg/image/upload/v1701696545/ib-world-school-logo-2-colour.png", class:'ib-img'%>
    <% end -%>
  </div>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <div class="dropdown show d-none d-xl-block">
      <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Sobre Nosotros
      </a>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <%= link_to 'Quiénes somos', about_path, class: 'dropdown-item' %>
        <%= link_to 'Nuestra Historia', historia_path, class: 'dropdown-item' %>
        <%= link_to 'Autoridades', autoridades_path, class: 'dropdown-item' %>
      </div>
    </div>

    <div class="dropdown show d-none d-xl-block">
      <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLinkThree" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Niveles Educacionales
      </a>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuLinkThree">
        <%= link_to 'Nivel Inicial', oferta_academica_path(anchor: 'inicial'), class: 'dropdown-item' %>
        <%= link_to 'Nivel Primario', oferta_academica_path(anchor: 'primario'), class: 'dropdown-item' %>
        <%= link_to 'Nivel Secundario', oferta_academica_path(anchor: 'secundario'), class: 'dropdown-item' %>
      </div>
    </div>

    <div class="dropdown show d-none d-xl-block">
      <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLinkThree" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Experiencias Educativas
      </a>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuLinkThree">
        <%= link_to 'Actividades Deportivas y Recreativas', experiencia_educativa_path(anchor: 'actividades_deportivas'), class: 'dropdown-item' %>
        <%= link_to 'Clases Abiertas', experiencia_educativa_path(anchor: 'clases_abiertas'), class: 'dropdown-item' %>
        <%= link_to 'Fiesta de los Colores', experiencia_educativa_path(anchor: 'fiesta_colores'), class: 'dropdown-item' %>
        <%= link_to 'Obras de Teatro', experiencia_educativa_path(anchor: 'obras_teatro'), class: 'dropdown-item' %>
        <%= link_to 'Salidas Educativas', experiencia_educativa_path(anchor: 'salidas_educativas'), class: 'dropdown-item' %>
        <%= link_to 'Contacto con la Naturaleza', experiencia_educativa_path(anchor: 'contacto_naturaleza'), class: 'dropdown-item' %>
        <%= link_to 'Arte y Creatividad', experiencia_educativa_path(anchor: 'arte_creatividad'), class: 'dropdown-item' %>
        <%= link_to 'Talleres', experiencia_educativa_path(anchor: 'talleres'), class: 'dropdown-item' %>
      </div>
    </div>
    <div class="d-lg-block d-xl-none">
      <a class="nav-link" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Sobre Nosotros
      </a>
      <div class="collapse" id="collapseExample">
        <%= link_to 'Quiénes somos', about_path, class: 'nav-link' %>
        <%= link_to 'Nuestra Historia', historia_path, class: 'nav-link' %>
        <%= link_to 'Autoridades', autoridades_path, class: 'nav-link' %>
      </div>

      <a class="nav-link" data-toggle="collapse" href="#collapseExampleTwo" role="button" aria-expanded="false" aria-controls="collapseExampleTwo">
        Niveles Educacionales
      </a>
      <div class="collapse" id="collapseExampleTwo">
        <%= link_to 'Nivel Inicial', oferta_academica_path(anchor: 'inicial'), class: 'nav-link' %>
        <%= link_to 'Nivel Primario', oferta_academica_path(anchor: 'primario'), class: 'nav-link' %>
        <%= link_to 'Nivel Secundario', oferta_academica_path(anchor: 'secundario'), class: 'nav-link' %>
      </div>

      <a class="nav-link" data-toggle="collapse" href="#collapseExampleThree" role="button" aria-expanded="false" aria-controls="collapseExampleThree">
        Experiencias Educativas
      </a>
      <div class="collapse" id="collapseExampleThree">
        <%= link_to 'Actividades Deportivas y Recreativas', experiencia_educativa_path(anchor: 'actividades_deportivas'), class: 'nav-link' %>
        <%= link_to 'Clases Abiertas', experiencia_educativa_path(anchor: 'clases_abiertas'), class: 'nav-link' %>
        <%= link_to 'Fiesta de los Colores', experiencia_educativa_path(anchor: 'fiesta_colores'), class: 'nav-link' %>
        <%= link_to 'Obras de Teatro', experiencia_educativa_path(anchor: 'obras_teatro'), class: 'nav-link' %>
        <%= link_to 'Salidas Educativas', experiencia_educativa_path(anchor: 'salidas_educativas'), class: 'nav-link' %>
        <%= link_to 'Contacto con la Naturaleza', experiencia_educativa_path(anchor: 'contacto_naturaleza'), class: 'nav-link' %>
        <%= link_to 'Arte y Creatividad', experiencia_educativa_path(anchor: 'arte_creatividad'), class: 'nav-link' %>
        <%= link_to 'Talleres', experiencia_educativa_path(anchor: 'talleres'), class: 'nav-link' %>
      </div>
    </div>

    <%= link_to 'IB', ib_path, class: 'nav-link' %>
    <%= link_to "Novedades", articles_path, class: "nav-link" %>
    <%= link_to "Contacto", new_conection_path, class: "nav-link" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-xl navbar-light navbar-lewagon ">
  <div>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dw7ox75dg/image/upload/v1585140067/san_patricio_logo.png", class:'sp-img'%>
    <% end %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dw7ox75dg/image/upload/v1701696545/ib-world-school-logo-2-colour.png", class:'ib-img'%>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">



    <div class="dropdown show d-none d-xl-block">
      <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Sobre Nosotros
      </a>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <%= link_to 'Quiénes somos', about_path, class: 'dropdown-item' %>
        <%= link_to 'Nuestra Historia', historia_path, class: 'dropdown-item' %>
        <%= link_to 'Autoridades', autoridades_path, class: 'dropdown-item' %>
      </div>
    </div>

    <div class="dropdown show d-none d-xl-block">
      <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLinkThree" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Niveles Educacionales
      </a>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuLinkThree">
        <%= link_to 'Nivel Inicial', oferta_academica_path(anchor: 'inicial'), class: 'dropdown-item' %>
        <%= link_to 'Nivel Primario', oferta_academica_path(anchor: 'primario'), class: 'dropdown-item' %>
        <%= link_to 'Nivel Secundario', oferta_academica_path(anchor: 'secundario'), class: 'dropdown-item' %>
      </div>
    </div>

    <div class="dropdown show d-none d-xl-block">
      <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLinkThree" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Experiencias Educativas
      </a>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuLinkThree">
        <%= link_to 'Actividades Deportivas y Recreativas', experiencia_educativa_path(anchor: 'actividades_deportivas'), class: 'dropdown-item' %>
        <%= link_to 'Clases Abiertas', experiencia_educativa_path(anchor: 'clases_abiertas'), class: 'dropdown-item' %>
        <%= link_to 'Fiesta de los Colores', experiencia_educativa_path(anchor: 'fiesta_colores'), class: 'dropdown-item' %>
        <%= link_to 'Obras de Teatro', experiencia_educativa_path(anchor: 'obras_teatro'), class: 'dropdown-item' %>
        <%= link_to 'Salidas Educativas', experiencia_educativa_path(anchor: 'salidas_educativas'), class: 'dropdown-item' %>
        <%= link_to 'Contacto con la Naturaleza', experiencia_educativa_path(anchor: 'contacto_naturaleza'), class: 'dropdown-item' %>
        <%= link_to 'Arte y Creatividad', experiencia_educativa_path(anchor: 'arte_creatividad'), class: 'dropdown-item' %>
        <%= link_to 'Talleres', experiencia_educativa_path(anchor: 'talleres'), class: 'dropdown-item' %>
      </div>
    </div>
    <div class="d-lg-block d-xl-none">
      <a class="nav-link" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Sobre Nosotros
      </a>
      <div class="collapse" id="collapseExample">
        <%= link_to 'Quiénes somos', about_path, class: 'nav-link' %>
        <%= link_to 'Nuestra Historia', historia_path, class: 'nav-link' %>
        <%= link_to 'Autoridades', autoridades_path, class: 'nav-link' %>
      </div>

      <a class="nav-link" data-toggle="collapse" href="#collapseExampleTwo" role="button" aria-expanded="false" aria-controls="collapseExampleTwo">
        Niveles Educacionales
      </a>
      <div class="collapse" id="collapseExampleTwo">
        <%= link_to 'Nivel Inicial', oferta_academica_path(anchor: 'inicial'), class: 'nav-link' %>
        <%= link_to 'Nivel Primario', oferta_academica_path(anchor: 'primario'), class: 'nav-link' %>
        <%= link_to 'Nivel Secundario', oferta_academica_path(anchor: 'secundario'), class: 'nav-link' %>
      </div>

      <a class="nav-link" data-toggle="collapse" href="#collapseExampleThree" role="button" aria-expanded="false" aria-controls="collapseExampleThree">
        Experiencias Educativas
      </a>
      <div class="collapse" id="collapseExampleThree">
       <%= link_to 'Actividades Deportivas y Recreativas', experiencia_educativa_path(anchor: 'actividades_deportivas'), class: 'nav-link' %>
        <%= link_to 'Clases Abiertas', experiencia_educativa_path(anchor: 'clases_abiertas'), class: 'nav-link' %>
        <%= link_to 'Fiesta de los Colores', experiencia_educativa_path(anchor: 'fiesta_colores'), class: 'nav-link' %>
        <%= link_to 'Obras de Teatro', experiencia_educativa_path(anchor: 'obras_teatro'), class: 'nav-link' %>
        <%= link_to 'Salidas Educativas', experiencia_educativa_path(anchor: 'salidas_educativas'), class: 'nav-link' %>
        <%= link_to 'Contacto con la Naturaleza', experiencia_educativa_path(anchor: 'contacto_naturaleza'), class: 'nav-link' %>
        <%= link_to 'Arte y Creatividad', experiencia_educativa_path(anchor: 'arte_creatividad'), class: 'nav-link' %>
        <%= link_to 'Talleres', experiencia_educativa_path(anchor: 'talleres'), class: 'nav-link' %>
      </div>
    </div>

    <%= link_to 'IB', ib_path, class: 'nav-link' %>
    <%= link_to "Novedades", articles_path, class: "nav-link" %>
    <%= link_to "Contacto", new_conection_path, class: "nav-link" %>
  </div>
</div>

app/views/shared/_second-card.html.erb
<div class="second-card-article-3">
  <%= link_to article_path(article) do %>
  <img src="<%= article.photo %>" alt="">
  <h4><%= article.category %></h4>
  <h2><%= article.title.truncate(80) %></h2>
  <% end %>
</div>
<div class="main-card-article-2">
  <%= link_to article_path(article) do %>
  <img src="<%= article.photo %>" alt="">
  <h4><%= article.category %></h4>
  <h2><%= article.title %></h2>
  <% end %>
</div>

app/views/shared/_top.html.erb
<div class="top-wrapper">
  <div>
    <%= link_to documents_path do %>
    <p class="btn-top mb-0"><i class="fas fa-download"></i> Documentos</p>
    <% end %>
  </div>
  <div class="links-top">
    <a href="https://www.facebook.com/sanpatriciotucuman/" target='_blank'>
      <i class="fab fa-facebook"></i>
    </a>
    <a href="https://www.instagram.com/sanpatriciotucuman/" target='_blank'>
      <i class="fab fa-instagram"></i>
    </a>
    <a href="https://twitter.com/ib_sanpatricio" target='_blank'>
      <i class="fab fa-twitter"></i>
    </a>
  </div>
</div>

app/views/shared/_topbar.html.erb
<div class="top-wrapper">
  <div>
  </div>
  <div class="links-top">
    <a href="https://www.facebook.com/sanpatriciotucuman/" target='_blank'>
      <i class="fab fa-facebook"></i>
    </a>
    <a href="https://www.instagram.com/sanpatriciotucuman/" target='_blank'>
      <i class="fab fa-instagram"></i>
    </a>
    <a href="https://twitter.com/ib_sanpatricio" target='_blank'>
      <i class="fab fa-twitter"></i>
    </a>
  </div>
</div>