config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_prefix =>'auth'
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get '/autoridades', to: 'pages#autoridades'
  get '/historia', to: 'pages#historia'
  get 'ib', to: 'pages#ib'
  get '/mision', to: 'pages#mision'
  get '/inicial', to: 'pages#inicial'
  get '/oferta_academica', to: 'pages#oferta_academica'
  get '/experiencia_educativa', to: 'pages#experiencia_educativa'

  resources :articles do
    resources :galleries, only: [:show, :create]
  end
  resources :contacts, only: [:new, :create]
  resources :conections, exept: [:update, :edit]



  resources :events
  resources :users, only: [:show, :destroy, :new, :create]
  resources :categories
  resources :posts
  resources :divisions, only: :show
  resources :documents
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord

  validates :title, presence: true
  validates :category, presence: true
  has_many_attached :files

  paginates_per 12

  private

  def file_attach
    if file.attached? == false
      errors.add(:file, 'tiene que estar presente')
    end
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_document, only: %w[edit update destroy]

  def index
    @document_category = Document.all
    if params["category"]
      @documents = Document.where(category: params["category"]).page params[:page]
    else
      @documents = Document.order(created_at: :desc).page params[:page]
    end
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      flash[:notice] = "Creaste exitosamente el documento"
      redirect_to documents_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @document.update(document_params)
      flash[:notice] = "Actualizaste el documento"
      redirect_to documents_path
    else
      render :edit
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_path
  end

  private

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:title, :category, files: [])
  end
end

app/views/documents/_card.html.erb
<div class="p-3 mb-4 rounded" id="document-card">
  <div class="d-flex justify-content-between">
    <p class="font-weight-bold text-success mb-0"><%= document.category %></p>
    <p class="text-secondary mb-0"><%= document.created_at.in_time_zone("Buenos Aires").strftime('%d/%m/%y - %H:%M') %></p>
  </div>
  <h2 class="py-3 mb-0"><%= document.title %></h2>
  <% document&.files.each do |image| %>
  <%= link_to cl_image_path(image.key, flags: 'attachment'), download: "document.title" do %>
  <p class="mb-0" style="font-weight: bold; font-size: 12px;"><i class="fas fa-file-pdf h4 text-danger"></i> Descargar Archivo PDF</p>
  <% end %>
  <% end %>
  <% if user_signed_in? %>
  <% if current_user.admin? %>
  <%= link_to 'Editar Documento', edit_document_path(document), class: "badge badge-warning" %>
  <%= link_to 'Destruir Documento', document_path(document), method: :delete ,data: { confirm: 'Estas seguro?' }, class: "badge badge-danger" %>
  <% end %>
  <% end %>
</div>

app/views/documents/_form.html.erb
<%= simple_form_for @document do |f| %>
<%= f.input :title %>
<%= f.input :category %>
<%= f.input :files, as: :file, input_html: { multiple: true }, label: "Archivo PDF" %>
<%= f.submit 'Crear documento', class: "btn btn-primary btn-block mb-3" %>
<div class="text-right pt-3">
  <%= link_to 'Volver', user_path(current_user), class: "btn btn-secondary" %>
</div>
<% end %>

app/views/documents/edit.html.erb
<%= render 'shared/navbar' %>
<div class="container pt-5 pb-5">
  <div class="shadow-sm p-5 mt-5 mb-5">
    <h2 class="font-weight-bold text-center">Crear Documento</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/documents/index.html.erb
<%= render 'shared/navbar' %>
<h3 class="pt-5 pb-2 text-center font-weight-bold h1">Documentos</h3>
<div class="container pt-5 mb-5 pb-5">
  <div class="d-md-flex justify-content-between pb-5 mb-5">
    <div class="mr-md-3 pb-4">
      <% @document_category.uniq(&:category).each do |document|  %>
      <%= link_to document.category, documents_path(category: document.category), class: "rounded btn btn-block text-md-left", id: "btn-document" %>
      <% end %>
      <%= link_to "Todos", documents_path, class: "rounded btn btn-block text-md-left", id: "btn-document" %></p>
    </div>
    <div class="flex-grow-1">
      <% @documents.each do |document|  %>
      <%= render 'card', document: document %>
      <% end %>
    </div>
  </div>
  <div class="mt-5 pb-5">
    <%= paginate @documents %>
  </div>
</div>

app/views/documents/new.html.erb
<%= render 'shared/navbar' %>
<div class="container pt-5 pb-5">
  <div class="shadow-sm p-5 mt-5 mb-5">
    <h2 class="font-weight-bold text-center">Crear Documento</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/documents/show.html.erb
<h1>Documents#show</h1>
<p>Find me in app/views/documents/show.html.erb</p>