config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_prefix =>'auth'
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get '/autoridades', to: 'pages#autoridades'
  get '/historia', to: 'pages#historia'
  get 'ib', to: 'pages#ib'
  get '/mision', to: 'pages#mision'
  get '/inicial', to: 'pages#inicial'
  get '/oferta_academica', to: 'pages#oferta_academica'
  get '/experiencia_educativa', to: 'pages#experiencia_educativa'

  resources :articles do
    resources :galleries, only: [:show, :create]
  end
  resources :contacts, only: [:new, :create]
  resources :conections, exept: [:update, :edit]



  resources :events
  resources :users, only: [:show, :destroy, :new, :create]
  resources :categories
  resources :posts
  resources :divisions, only: :show
  resources :documents
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :title, presence: true
  validates :photo, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  def index
    @categories = Category.all
  end

  def show; end

  def new
    if current_user.admin?
      @category = Category.new
    else
      flash[:notice] = "Accesso denegado"
      redirect_to root_path
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "Eliminaste la categoria #{@category.title}"
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :photo)
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
<%= f.input :title %>
<%= f.input :photo %>
<%= f.submit 'Crear categoria', class: "btn btn-primary btn-block mb-3" %>
<div class="text-right pt-3">
  <%= link_to 'Volver', user_path(current_user), class: "btn btn-secondary" %>
</div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'shared/navbar' %>
<div class="container pt-5 pb-5">
  <div class="shadow-sm p-5 mt-5 mb-5">
    <h2 class="h3 py-3">Editar Categoria (notificaciones)</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/categories/index.html.erb
<%= render 'shared/main_navbar' %>
<div class="post-admin-container pt-5 pb-5">
  <div class="d-flex justify-content-between align-items-center">
    <h2>Categorias de notificaciones</h2>
    <%= link_to 'Crear categoria', new_category_path, class: "btn btn-primary" %>
  </div>
  <table class="table table-striped table-dark mt-5 mb-5">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Categorias</th>
        <th scope="col">Fecha</th>
        <th scope="col">Ver</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.created_at.strftime(' %d/%m/%y') %></td>
        <td><%= link_to 'Ver', category_path(category) %></td>
        <td class="text-right">
          <%= link_to 'Editar', edit_category_path(category), class: "btn btn-sm btn-warning mr-3" %>
          <%= link_to 'Eliminar', category_path(category), method: :delete, data: { confirm: 'Estas seguro que quieres destruir categoria?' } , class: "btn btn-sm btn-danger" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<%= render 'shared/navbar' %>
<div class="container pt-5 pb-5">
  <div class="shadow-sm p-5 mt-5 mb-5">
    <h2 class="font-weight-bold text-center">Crear Categoria (notificaciones)</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/categories/show.html.erb
<%= render 'shared/main_navbar' %>
<div class="articles-navbar">
  <h2>NOTIFICACIONES</h2>
</div>
<div class="post-index-container">
  <h2><%= @category.title %></h2>
  <% @category.posts.each do |post| %>
  <div class="post-cards">
   <%= link_to post_path(post) do %>
   <div class="post-card-title">
     <h1><%= post.title.truncate(80) %></h1>
     <p><%= post.created_at.strftime(' %d/%m/%y') %></p>
   </div>
   <div class="post-card-content">
    <p><%= post.content %></p>
   </div>
   <% end %>
  </div>
  <% end %>
</div>
<div class="text-center p-5 post-footer">
  <%= link_to 'Atras', user_path(current_user), class: 'btn-article'  %>
</div>